//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_TempBaseInfo
    {
        public decimal ID { get; set; }
        public string Asset_ID { get; set; }
        public string Asset_Name { get; set; }
        public string Asset_AliasName { get; set; }
        public Nullable<System.DateTime> Asset_UpdateTime { get; set; }
        public Nullable<System.DateTime> Asset_CreateTime { get; set; }
        public Nullable<decimal> Asset_Cost { get; set; }
        public Nullable<decimal> Asset_SumCost { get; set; }
        public string Asset_Genre { get; set; }
        public string Asset_GenreTwo { get; set; }
        public string Asset_Category { get; set; }
        public Nullable<decimal> Asset_Chapter { get; set; }
        public string Asset_Director { get; set; }
        public string Asset_Adaptor { get; set; }
        public string Asset_Actors { get; set; }
        public string Asset_Country { get; set; }
        public string Asset_Year { get; set; }
        public string Asset_MediaType { get; set; }
        public string Asset_resolution { get; set; }
        public string Asset_PRunDate { get; set; }
        public Nullable<System.DateTime> Asset_RunDate { get; set; }
        public string Online_Pdate { get; set; }
        public Nullable<System.DateTime> Online_Date { get; set; }
        public Nullable<System.DateTime> Broad_Date { get; set; }
        public string Asset_Platform { get; set; }
        public string Synchrono_Lever { get; set; }
        public string Asset_Subtitle { get; set; }
        public string Asset_Language { get; set; }
        public string Subtitle_Status { get; set; }
        public string Asset_Manufaction { get; set; }
        public Nullable<decimal> Asset_TicketOffice { get; set; }
        public string TicketOffice_Lever { get; set; }
        public Nullable<decimal> Asset_RunTime { get; set; }
        public string Asset_Payment { get; set; }
        public Nullable<int> Asset_CheckStatus { get; set; }
        public string CurContract_ID { get; set; }
        public string Op_Person { get; set; }
        public string Op_Department { get; set; }
        public string Asset_Memo { get; set; }
        public Nullable<decimal> RightInfo_ID { get; set; }
        public string Buy_Type { get; set; }
        public string Name_EN { get; set; }
        public string Short_Description { get; set; }
        public string Description { get; set; }
        public string Producter_CH { get; set; }
        public string Producter_EN { get; set; }
        public string Provider_CH { get; set; }
        public string Provider_EH { get; set; }
        public string Provider { get; set; }
        public string License { get; set; }
        public Nullable<int> Arv_File { get; set; }
        public Nullable<System.DateTime> File_Date { get; set; }
        public string Sale_Range { get; set; }
        public string Sale_Area { get; set; }
        public Nullable<System.DateTime> Check_endtime { get; set; }
        public string Contract_No { get; set; }
        public string Made_Area { get; set; }
        public string BuyAttributes { get; set; }
        public string Contentlevel { get; set; }
        public string PrizeInfo { get; set; }
        public string ContentKeywords { get; set; }
        public Nullable<decimal> F1_Price { get; set; }
        public Nullable<decimal> F2_Price { get; set; }
        public Nullable<decimal> F3_Price { get; set; }
        public Nullable<decimal> F4_Price { get; set; }
        public Nullable<decimal> F5_Price { get; set; }
        public Nullable<decimal> F6_Price { get; set; }
        public Nullable<decimal> F7_Price { get; set; }
        public string Is_PreSell { get; set; }
        public string Update_Person { get; set; }
    }
}
