//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Detail
    {
        public long Id { get; set; }
        public string ContractSerial { get; set; }
        public string ContractNumber { get; set; }
        public string Asset_Id { get; set; }
        public string Asset_Name { get; set; }
        public string Asset_Director { get; set; }
        public string Asset_Year { get; set; }
        public string Asset_Genre { get; set; }
        public decimal Asset_Price { get; set; }
        public int Asset_Chapter { get; set; }
        public decimal Asset_Amount { get; set; }
        public decimal Asset_Amount_Exch { get; set; }
        public Nullable<int> Authorize_Life { get; set; }
        public Nullable<System.DateTime> Authorize_StartDate { get; set; }
        public Nullable<System.DateTime> Authorize_EndDate { get; set; }
        public decimal EstimateAmount { get; set; }
        public Nullable<decimal> EstimateAmount_Exch { get; set; }
        public decimal TaxRate { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal Asset_AmountNoTax { get; set; }
        public decimal Asset_AmountTax { get; set; }
        public int Status { get; set; }
        public int IsReplacement { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Mender { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string assetAmortizeYYMM { get; set; }
        public string assetAmortizeStat { get; set; }
        public string FilmDate { get; set; }
        public string excutionStat { get; set; }
        public Nullable<System.DateTime> excutionLastDate { get; set; }
    }
}
