//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_BaseInfo
    {
        public long Id { get; set; }
        public string ContractSerial { get; set; }
        public string ParentSerial { get; set; }
        public string ContractNumber { get; set; }
        public string ContractName { get; set; }
        public string PartyId { get; set; }
        public string PartyName { get; set; }
        public int ContractType { get; set; }
        public int ContractNature { get; set; }
        public string SecondaryContractNature { get; set; }
        public decimal ContractAmount { get; set; }
        public Nullable<decimal> ContractAmountExch { get; set; }
        public decimal ContractAmountNoTax { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> PaymentAmountExch { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string AccountID { get; set; }
        public string DeptId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> EstimateAmount { get; set; }
        public decimal EstimateAmount_Exch { get; set; }
        public string SealTypeId { get; set; }
        public int InvoiceTypeId { get; set; }
        public int CurrencyTypeId { get; set; }
        public decimal CurrencyExchRate { get; set; }
        public int TaxRate { get; set; }
        public int PaymentTypeId { get; set; }
        public int ExamineFlowId { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public int AuditingStatus { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Mender { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string AmortizeStat { get; set; }
        public string MyCompanyId { get; set; }
        public string MyCompany { get; set; }
        public int FileStatus { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public int FileCount { get; set; }
        public string FileRemark { get; set; }
        public string FileCreator { get; set; }
        public string RightListName { get; set; }
        public string AuthorizeLifeName { get; set; }
        public string EstimatedFilingTime { get; set; }
    
        public virtual Contract_BaseInfo Contract_BaseInfo1 { get; set; }
        public virtual Contract_BaseInfo Contract_BaseInfo2 { get; set; }
    }
}
