//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NFineBaseEntities : DbContext
    {
        public NFineBaseEntities()
            : base("name=NFineBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset_TempBaseInfo> Asset_TempBaseInfo { get; set; }
        public virtual DbSet<Contract_BaseInfo> Contract_BaseInfo { get; set; }
        public virtual DbSet<Contract_Detail> Contract_Detail { get; set; }
    }
}
