//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_Center
    {
        public int Id { get; set; }
        public Nullable<int> MessageType { get; set; }
        public string MessageTitle { get; set; }
        public string MessageContent { get; set; }
        public int Status { get; set; }
        public int OpStatus { get; set; }
        public string ReceiveUserId { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Mender { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<int> IsProcessed { get; set; }
        public Nullable<long> MaxReqDetailId { get; set; }
    }
}
